# -*- coding: utf-8 -*-
"""Text to Speech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c6VR0VG2M-_q0uOmCXvCzpiFaJruIvN4
"""

# !pip install gTTS

from gtts import gTTS

text_to_say = "Hello World"
language = "en"

gtts_object = gTTS(text=text_to_say, lang=language, slow=False)
gtts_object.save("/content/gtts.wav")

from IPython.display import Audio

Audio("/content/gtts.wav")

Italian_text = "It is a Ferrari, scaled down version of God."
Italian_lang = "it"

italian_gtts_object = gTTS(text = Italian_text,
                           lang = Italian_lang,
                           slow = "True")

italian_gtts_object.save("/content/italian.wav")

Audio("/content/italian.wav")